ALTER TABLE `performance_submissions`
  MODIFY COLUMN `status` ENUM('DRAFT', 'MENUNGGU_BUKTI', 'MENUNGGU_VALIDASI_KATIM', 'DISETUJUI', 'DITOLAK_KATIM', 'REVISI_KATIM', 'SUBMITTED_TO_KATIM', 'REVISION_BY_KATIM', 'SUBMITTED_TO_KAPOKJA', 'REVISION_BY_KAPOKJA', 'APPROVED') NOT NULL DEFAULT 'DRAFT';
